# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('child_interest', models.TextField(max_length=1000)),
                ('school_district_or_town_name', models.CharField(max_length=200)),
                ('zip_code', models.PositiveSmallIntegerField(default=0)),
                ('years_of_FIRST_experience', models.PositiveSmallIntegerField(default=0)),
                ('interested_in_stem_project', models.BooleanField()),
                ('interested_in_building', models.BooleanField()),
                ('interested_in_programming', models.BooleanField()),
                ('interested_in_outreach', models.BooleanField()),
                ('first_update', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('update_count', models.PositiveIntegerField()),
                ('looking_request_count', models.PositiveIntegerField()),
                ('requested_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_program', models.CharField(choices=[('L', 'FLL'), ('T', 'FTC'), ('R', 'FRC')], default='L', max_length=1)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('school_base_team', models.BooleanField()),
                ('school_district_or_town_name', models.CharField(max_length=200)),
                ('zip_code', models.PositiveSmallIntegerField(default=0)),
                ('year_founded', models.PositiveSmallIntegerField(default=2017)),
                ('description', models.TextField(max_length=1000)),
                ('achievement', models.TextField(max_length=1000)),
                ('web_site', models.URLField()),
                ('looking_for_teammate', models.BooleanField()),
                ('looking_for_teammate_stem_project', models.BooleanField()),
                ('looking_for_teammate_build', models.BooleanField()),
                ('looking_for_teammate_prog', models.BooleanField()),
                ('looking_for_teammate_outreach', models.BooleanField()),
                ('looking_for_mentoring_opportunities', models.BooleanField()),
                ('looking_for_outreach_opportunities', models.BooleanField()),
                ('first_update', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('update_count', models.PositiveIntegerField()),
                ('looking_request_count', models.PositiveIntegerField()),
                ('requested_count', models.PositiveIntegerField()),
            ],
        ),
    ]
