# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='town_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='town_name',
        ),
        migrations.AddField(
            model_name='team',
            name='school_based_team',
            field=models.BooleanField(default=False, help_text='Select if your team is restricted to members living in the school district.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.PositiveSmallIntegerField(help_text='5 digit ZIP code of where you live.', validators=[match.models.validate_zip_code]),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_program',
            field=models.CharField(choices=[('-', '-'), ('J', 'jFLL'), ('L', 'FLL'), ('T', 'FTC'), ('R', 'FRC')], default='-', max_length=1, validators=[match.models.validate_first_program]),
        ),
        migrations.AlterField(
            model_name='team',
            name='looking_request_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='requested_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='school_district_name',
            field=models.CharField(blank=True, help_text='Enter the name of your school district if your team is a school-based team. Otherwise, leave the field blank.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='update_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='zip_code',
            field=models.PositiveSmallIntegerField(help_text='5 digit ZIP code of where you meet.', validators=[match.models.validate_zip_code]),
        ),
    ]
