# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20170307_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitor_username', models.CharField(max_length=200)),
                ('prospective_username', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('P', 'person to team'), ('T', 'team to person'), ('H', 'new team to mentor team'), ('M', 'mentor team to new team')], default='P', max_length=1)),
                ('status', models.CharField(choices=[('I', 'initiated'), ('A', 'accepted'), ('D', 'declined'), ('E', 'expired')], default='I', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='child_name',
            field=models.CharField(help_text='Enter the name of the child that you are looking a team for.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='looking_request_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='requested_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
