# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20170311_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='cached_zip_code',
            new_name='zip_code_cached',
        ),
    ]
