# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20170308_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='status',
            field=models.CharField(choices=[('I', 'initiated'), ('A', 'accepted'), ('D', 'declined'), ('O', 'declined that has now expired'), ('E', 'expired')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='child_interest',
            field=models.TextField(help_text="Enter your child's interest and relevant experience. Write description to read as a paragraph.", max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='achievement',
            field=models.TextField(help_text='Describe your recent achievements. Write description to read as a paragraph.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(help_text="Enter a brief team's description and include your team's objectives. Write description to read as a paragraph.", max_length=2000),
        ),
    ]
