# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_auto_20170311_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='zip_code_cached',
        ),
        migrations.RemoveField(
            model_name='team',
            name='zip_code_cached',
        ),
        migrations.AlterField(
            model_name='person',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='person',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='person',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='town_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='team',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='town_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
