# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import match.models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_auto_20170312_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='date',
            new_name='date_invited',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school_based_team',
        ),
        migrations.AddField(
            model_name='invite',
            name='date_response',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('-', '-'), ('S', 'school based'), ('H', '4H club'), ('B', 'boy scout'), ('G', 'girl scout'), ('O', 'other')], default='-', help_text='Enter the type of association that your team is part of.  School-based teams typically restrict membership to children living in the school district.', max_length=1, validators=[match.models.validate_team_type]),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_program',
            field=models.CharField(choices=[('-', '-'), ('J', 'jFLL'), ('L', 'FLL'), ('T', 'FTC'), ('R', 'FRC')], default='-', help_text='Enter the FIRST program that the team participate in.', max_length=1, validators=[match.models.validate_first_program]),
        ),
    ]
